
#pragma once

/*
*	Generated By SQLTOOL, Don't Edit This File
*
*/

#include "table.h"
#include "field/field.h"

namespace MysqlUtil
{
// table
class t_datakey : public SQLTable
{
private:
    t_datakey() : SQLTable("t_datakey"),
		dataKeyID(ftVarString, "dataKeyID", 0, false),
		ownerSrcId(ftVarString, "ownerSrcId", 1, false),
		elements(ftBlob, "elements", 2, false),
		createTime(ftDatetime, "createTime", 3, false),
		testVersion(ftLong, "testVersion", 4, false)

	{
		fieldList_.push_back(dataKeyID);
		fieldList_.push_back(ownerSrcId);
		fieldList_.push_back(elements);
		fieldList_.push_back(createTime);
		fieldList_.push_back(testVersion);

    };

public:
	~t_datakey() {}
	
    static const t_datakey& GetInstance()
    {
		static t_datakey Instance;
        return Instance;
    }

    // fields start
	 const Field dataKeyID;
	 const Field ownerSrcId;
	 const Field elements;
	 const Field createTime;
	 const Field testVersion;

    // fields end

};


}; // namespace
