
#pragma once

/*
*	Generated By SQLTOOL, Don't Edit This File
*
*/

#include "table.h"
#include "field/field.h"

namespace MysqlUtil
{
// table
class t_licKey : public SQLTable
{
private:
    t_licKey() : SQLTable("t_licKey"),
		licKeyId(ftVarString, "licKeyId", 0, false),
		ownerSrcId(ftVarString, "ownerSrcId", 1, false),
		pubKeyId(ftVarString, "pubKeyId", 2, false),
		startTime(ftTimestamp, "startTime", 3, false),
		endTime(ftTimestamp, "endTime", 4, false),
		algoType(ftLong, "algoType", 5, false),
		createTime(ftDatetime, "createTime", 6, false),
		testVersion(ftLong, "testVersion", 7, false)

	{
		fieldList_.push_back(licKeyId);
		fieldList_.push_back(ownerSrcId);
		fieldList_.push_back(pubKeyId);
		fieldList_.push_back(startTime);
		fieldList_.push_back(endTime);
		fieldList_.push_back(algoType);
		fieldList_.push_back(createTime);
		fieldList_.push_back(testVersion);

    };

public:
	~t_licKey() {}
	
    static const t_licKey& GetInstance()
    {
		static t_licKey Instance;
        return Instance;
    }

    // fields start
	 const Field licKeyId;
	 const Field ownerSrcId;
	 const Field pubKeyId;
	 const Field startTime;
	 const Field endTime;
	 const Field algoType;
	 const Field createTime;
	 const Field testVersion;

    // fields end

};


}; // namespace
