
#pragma once

/*
*	Generated By SQLTOOL, Don't Edit This File
*
*/

#include "table.h"
#include "field/field.h"

namespace MysqlUtil
{
// table
class t_userinfo1 : public SQLTable
{
private:
    t_userinfo1() : SQLTable("t_userinfo1"),
		srcId(ftVarString, "srcId", 0, false),
		appId(ftVarString, "appId", 1, false),
		createTime(ftDatetime, "createTime", 2, false)

	{
		fieldList_.push_back(srcId);
		fieldList_.push_back(appId);
		fieldList_.push_back(createTime);

    };

public:
	~t_userinfo1() {}
	
    static const t_userinfo1& GetInstance()
    {
		static t_userinfo1 Instance;
        return Instance;
    }

    // fields start
	 const Field srcId;
	 const Field appId;
	 const Field createTime;

    // fields end

};


}; // namespace
