
#pragma once

/*
*	Generated By SQLTOOL, Don't Edit This File
*
*/

#include "table.h"
#include "field/field.h"

namespace MysqlUtil
{
// table
class t_userinfo : public SQLTable
{
private:
    t_userinfo() : SQLTable("t_userinfo"),
		srcId(ftVarString, "srcId", 0, false),
		appId(ftVarString, "appId", 1, false),
		createTime(ftDatetime, "createTime", 2, false),
		testVersion(ftLong, "testVersion", 3, false)

	{
		fieldList_.push_back(srcId);
		fieldList_.push_back(appId);
		fieldList_.push_back(createTime);
		fieldList_.push_back(testVersion);

    };

public:
	~t_userinfo() {}
	
    static const t_userinfo& GetInstance()
    {
		static t_userinfo Instance;
        return Instance;
    }

    // fields start
	 const Field srcId;
	 const Field appId;
	 const Field createTime;
	 const Field testVersion;

    // fields end

};


}; // namespace
