
#pragma once

/*
*	Generated By SQLTOOL, Don't Edit This File
*
*/

#include "table.h"
#include "field/field.h"

namespace MysqlUtil
{
// table
class t_userkey : public SQLTable
{
private:
    t_userkey() : SQLTable("t_userkey"),
		userKeyId(ftVarString, "userKeyId", 0, false),
		ownerSrcId(ftVarString, "ownerSrcId", 1, false),
		storageType(ftLong, "storageType", 2, false),
		createTime(ftDatetime, "createTime", 3, false),
		testVersion(ftLong, "testVersion", 4, false)

	{
		fieldList_.push_back(userKeyId);
		fieldList_.push_back(ownerSrcId);
		fieldList_.push_back(storageType);
		fieldList_.push_back(createTime);
		fieldList_.push_back(testVersion);

    };

public:
	~t_userkey() {}
	
    static const t_userkey& GetInstance()
    {
		static t_userkey Instance;
        return Instance;
    }

    // fields start
	 const Field userKeyId;
	 const Field ownerSrcId;
	 const Field storageType;
	 const Field createTime;
	 const Field testVersion;

    // fields end

};


}; // namespace
